# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "ke_auto_profile_switcher"
version = "0.1.3"
authors = ["HIRAKI Satoru <saruko313@gmail.com>"]
repository = "https://github.com/Layzie/ke_auto_profile_switcher"
description = "This CLI automatically switches Karabiner-Elements profiles with and without USB keyboard connection"
categories = ["command-line-utilities"]
keywords = ["cli", "karabiner-elements"]
license = "MIT"
readme = "README.md"
edition = "2021"

[[bin]]
name = "kaps"
path = "src/main.rs"

[dependencies]
usb_enumeration =  "0.1.2"
clap = { version = "3.1.18", features = ["derive"] }
