name: Release to crates.io (trusted publishing)

on: create

jobs:
  publish:
    if: github.event.ref_type == 'tag' && startsWith(github.event.ref, 'v')
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libudev-dev
      
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      
      - name: Publish to crates.io using trusted publishing
        run: cargo publish --no-interactive